export type SupplierStatus = 'Active' | 'Inactive'
export type ReceivableType = 'AdvancePayment' | 'ShipmentPayment' | 'AcceptancePayment' | 'WarrantyRetention' | 'ProgressPayment' | 'Other'
export type FinanceBalanceStatus = 'NotDue' | 'PartiallyPaid' | 'Paid' | 'Overdue' | 'PartiallyOverdue'
export type PaymentMethod = 'BankTransfer' | 'Cash' | 'Cheque' | 'Other'
export type PayableType = 'AdvancePayment' | 'DeliveryPayment' | 'AcceptancePayment' | 'RetentionPayment' | 'PurchasePayment' | 'Other'
export type PaymentStatus = 'Unpaid' | 'PartiallyPaid' | 'Paid'
export type PurchaseOrderStatus = 'Draft' | 'Ordered' | 'PartiallyReceived' | 'Received' | 'Cancelled'
export type ShipmentStatus = 'Preparing' | 'Shipped' | 'InTransit' | 'Received' | 'Cancelled'

export interface Page<T> { items: T[]; page: number; pageSize: number; total: number }
export interface SupplierSummary { id: number; code: string; name: string; shortName?: string; status: SupplierStatus; category?: string; contactName?: string; contactMethod?: string; totalPurchased: number; totalPaid: number; outstandingPayable: number; isArchived: boolean; version: number; updatedAtUtc: string }
export interface SupplierDetails extends SupplierSummary { mobile?: string; phone?: string; email?: string; weChat?: string; province?: string; city?: string; address?: string; paymentTerms?: string; creditDays: number; bankName?: string; bankAccountName?: string; remark?: string; totalPayable: number; allocatedPaid: number; unallocatedPaid: number; overduePayable: number; notDuePayable: number; archivedAtUtc?: string; createdAtUtc: string }
export interface SupplierInput { name: string; shortName?: string; status: SupplierStatus; category?: string; contactName?: string; mobile?: string; phone?: string; email?: string; weChat?: string; province?: string; city?: string; address?: string; paymentTerms?: string; creditDays: number; bankName?: string; bankAccountName?: string; remark?: string }
export interface SupplierUpdateInput extends SupplierInput { version: number }

export interface PurchaseOrderSummary { id: number; code: string; supplierId: number; supplierCode: string; supplierName: string; projectId: number; projectCode: string; projectName: string; orderDate: string; status: PurchaseOrderStatus; totalAmount: number; expectedDeliveryDate?: string | null; orderedQuantity: number; receivedQuantity: number; receiptProgress: number; itemCount: number; receivedItemCount: number; partiallyReceivedItemCount: number; notReceivedItemCount: number; createdByDisplayName?: string | null; isArchived: boolean; version: number; updatedAtUtc: string }
export interface PurchaseOrderItemDetails { id: number; itemName: string; manufacturer?: string | null; model?: string | null; specification?: string | null; quantity: number; unit: string; unitPrice: number; amount: number; receivedQuantity: number; remainingQuantity: number; receiptStatus: 'NotReceived' | 'PartiallyReceived' | 'Received'; remark?: string | null; version: number }
export interface PurchaseReceiptItemDetails { id: number; purchaseOrderItemId: number; itemName: string; unit: string; quantityReceived: number }
export interface PurchaseReceiptDetails { id: number; code: string; purchaseOrderId: number; receivedDate: string; receivedByUserId: number; receivedByDisplayName: string; remark?: string | null; createdAtUtc: string; items: PurchaseReceiptItemDetails[] }
export interface PurchaseOrderDetails extends PurchaseOrderSummary { contactName?: string | null; deliveryAddress?: string | null; remark?: string | null; archivedAtUtc?: string | null; createdAtUtc: string; items: PurchaseOrderItemDetails[]; receipts: PurchaseReceiptDetails[] }
export interface PurchaseOrderItemInput { id?: number | null; itemName: string; manufacturer?: string | null; model?: string | null; specification?: string | null; quantity: number; unit: string; unitPrice: number; remark?: string | null }
export interface PurchaseOrderInput { supplierId: number; projectId: number; orderDate: string; contactName?: string | null; deliveryAddress?: string | null; expectedDeliveryDate?: string | null; remark?: string | null; items: PurchaseOrderItemInput[] }
export interface PurchaseOrderUpdateInput extends PurchaseOrderInput { version: number }
export interface PurchaseReceiptInput { receivedDate: string; remark?: string | null; items: Array<{ purchaseOrderItemId: number; quantityReceived: number }>; purchaseOrderVersion: number }

export interface ReceivableSummary { id: number; code: string; customerId: number; customerName: string; projectId: number; projectCode: string; projectName: string; title: string; receivableType: ReceivableType; amount: number; allocatedAmount: number; outstandingAmount: number; dueDate: string; status: FinanceBalanceStatus; overdueDays: number; isArchived: boolean; version: number; updatedAtUtc: string }
export interface ReceiptAllocationDetails { id: number; receiptId: number; receivableId: number; receivableCode: string; receivableTitle: string; projectId: number; projectCode: string; projectName: string; receivableType: ReceivableType; receivableAmount: number; receiptCode: string; receiptDate: string; receiptAmount: number; allocatedAmount: number; createdByDisplayName?: string; isCancelled: boolean; version: number; createdAtUtc: string; cancelledAtUtc?: string }
export interface ReceivableDetails extends ReceivableSummary { customerCode: string; projectContractAmount: number; description?: string; remark?: string; archivedAtUtc?: string; createdAtUtc: string; allocations: ReceiptAllocationDetails[] }
export interface ReceivableInput { customerId: number; projectId: number; title: string; receivableType: ReceivableType; amount: number; dueDate: string; description?: string; remark?: string }
export interface ReceivableUpdateInput { title: string; receivableType: ReceivableType; amount: number; dueDate: string; description?: string; remark?: string; version: number }

export interface ReceiptSummary { id: number; code: string; customerId: number; customerName: string; receiptDate: string; amount: number; allocatedAmount: number; unallocatedAmount: number; paymentMethod: PaymentMethod; bankReference?: string; payerName?: string; isArchived: boolean; version: number; updatedAtUtc: string }
export interface ReceiptDetails extends ReceiptSummary { customerCode: string; remark?: string; archivedAtUtc?: string; createdAtUtc: string; allocations: ReceiptAllocationDetails[] }
export interface ReceiptInput { customerId: number; receiptDate: string; amount: number; paymentMethod: PaymentMethod; bankReference?: string; payerName?: string; remark?: string }
export interface ReceiptUpdateInput { receiptDate: string; amount: number; paymentMethod: PaymentMethod; bankReference?: string; payerName?: string; remark?: string; version: number }

export interface PayableSummary { id: number; code: string; supplierId: number; supplierCode: string; supplierName: string; projectId: number; projectCode: string; projectName: string; purchaseOrderId?: number | null; purchaseOrderCode?: string | null; payableType: PayableType; title: string; amount: number; allocatedAmount: number; remainingAmount: number; dueDate: string; paymentStatus: PaymentStatus; isOverdue: boolean; overdueDays: number; isArchived: boolean; version: number; updatedAtUtc: string }
export interface PaymentAllocationDetails { id: number; paymentId: number; paymentCode: string; paymentDate: string; paymentAmount: number; paymentMethod: PaymentMethod; payableId: number; payableCode: string; payableType: PayableType; payableTitle: string; payableAmount: number; projectId: number; projectCode: string; projectName: string; purchaseOrderId?: number | null; purchaseOrderCode?: string | null; allocatedAmount: number; createdByDisplayName?: string | null; isCancelled: boolean; cancelledByDisplayName?: string | null; version: number; createdAtUtc: string; cancelledAtUtc?: string | null }
export interface PayableDetails extends PayableSummary { remark?: string | null; archivedAtUtc?: string | null; createdAtUtc: string; allocations: PaymentAllocationDetails[] }
export interface PayableInput { supplierId: number; projectId: number; purchaseOrderId?: number | null; payableType: PayableType; title: string; amount: number; dueDate: string; remark?: string | null }
export interface PayableUpdateInput extends PayableInput { version: number }

export interface PaymentSummary { id: number; code: string; supplierId: number; supplierCode: string; supplierName: string; paymentDate: string; amount: number; allocatedAmount: number; unallocatedAmount: number; paymentMethod: PaymentMethod; payeeName?: string | null; bankReference?: string | null; isArchived: boolean; version: number; updatedAtUtc: string }
export interface PaymentDetails extends PaymentSummary { remark?: string | null; archivedAtUtc?: string | null; createdAtUtc: string; allocations: PaymentAllocationDetails[] }
export interface PaymentInput { supplierId: number; paymentDate: string; amount: number; paymentMethod: PaymentMethod; payeeName?: string | null; bankReference?: string | null; remark?: string | null }
export interface PaymentUpdateInput extends PaymentInput { version: number }
export interface PayablePlanItemInput { payableType: PayableType; title: string; amount: number; dueDate: string; remark?: string | null }

export interface ShipmentSummary { id: number; code: string; customerId: number; customerCode: string; customerName: string; projectId: number; projectCode: string; projectName: string; shipmentDate: string; status: ShipmentStatus; receiverName?: string | null; logisticsCompany?: string | null; trackingNumber?: string | null; signedAtUtc?: string | null; itemCount: number; equipmentCount: number; isArchived: boolean; version: number; updatedAtUtc: string }
export interface ShipmentItemDetails { id: number; equipmentId?: number | null; equipmentCode?: string | null; itemName: string; manufacturer?: string | null; model?: string | null; quantity: number; unit: string; remark?: string | null; version: number }
export interface ShipmentDetails extends ShipmentSummary { receiverMobile?: string | null; shippingAddress: string; remark?: string | null; archivedAtUtc?: string | null; createdAtUtc: string; items: ShipmentItemDetails[] }
export interface ShipmentItemInput { id?: number | null; equipmentId?: number | null; itemName: string; manufacturer?: string | null; model?: string | null; quantity: number; unit: string; remark?: string | null }
export interface ShipmentInput { customerId: number; projectId: number; shipmentDate: string; receiverName?: string | null; receiverMobile?: string | null; logisticsCompany?: string | null; trackingNumber?: string | null; shippingAddress: string; remark?: string | null; items: ShipmentItemInput[] }
export interface ShipmentUpdateInput extends ShipmentInput { version: number }
export interface ShipmentEquipmentCandidate { id: number; code: string; name: string; manufacturer?: string | null; model?: string | null; isDelivered: boolean; shipmentCode?: string | null }
export interface ProjectShipmentMetrics { projectId: number; shipmentCount: number; receivedShipmentCount: number; equipmentDeliveryCount: number; totalEquipmentCount: number; allEquipmentDelivered: boolean; lastShipmentDate?: string | null }
export interface EquipmentShipmentLookup { equipmentId: number; isShipped: boolean; shipment?: ShipmentSummary | null }

export interface FinanceConsistencyWarning { code: string; message: string; count: number }
export interface ProjectReceiptAllocationSummary { allocationId: number; receiptId: number; receiptCode: string; receiptDate: string; receiptAmount: number; receivableId: number; receivableCode: string; allocatedAmount: number; allocatedAtUtc: string }
export interface ProjectPaymentAllocationSummary { allocationId: number; paymentId: number; paymentCode: string; paymentDate: string; paymentAmount: number; payableId: number; payableCode: string; allocatedAmount: number; allocatedAtUtc: string }
export interface ProjectShipmentSummary { shipmentId: number; shipmentCode: string; shipmentDate: string; status: ShipmentStatus; itemCount: number; equipmentCount: number }
export interface CustomerProjectFinanceRow { projectId: number; projectCode: string; projectName: string; projectStatus: 'Planning' | 'Active' | 'OnHold' | 'Completed' | 'Cancelled'; contractAmount: number; receivableAmount: number; receivedAllocatedAmount: number; receivableOutstandingAmount: number; receivableOverdueAmount: number; purchaseAmount: number; payableAmount: number; paidAllocatedAmount: number; grossProfit: number; grossMargin?: number | null; updatedAtUtc: string }
export interface CustomerFinanceOverview { customerId: number; customerCode: string; customerName: string; projectCount: number; activeProjectCount: number; contractAmount: number; receiptAmount: number; receivedAllocatedAmount: number; unallocatedReceiptAmount: number; receivableAmount: number; receivableOutstandingAmount: number; receivableOverdueAmount: number; receivableNotDueAmount: number; purchaseAmount: number; payableAmount: number; paidAllocatedAmount: number; payableOutstandingAmount: number; payableOverdueAmount: number; payableNotDueAmount: number; shipmentCount: number; receivedShipmentCount: number; lastShipmentDate?: string | null; estimatedGrossProfit: number; estimatedGrossMargin?: number | null; warnings: FinanceConsistencyWarning[] }
export interface ProjectFinanceOverview { projectId: number; customerId: number; projectCode: string; projectName: string; customerCode: string; customerName: string; contractAmount: number; receivableAmount: number; receivedAllocatedAmount: number; receivableOutstandingAmount: number; receivableOverdueAmount: number; receivableNotDueAmount: number; purchaseAmount: number; purchaseOrderCount: number; purchaseReceiptCount: number; payableAmount: number; paidAllocatedAmount: number; payableOutstandingAmount: number; payableOverdueAmount: number; payableNotDueAmount: number; shipmentCount: number; receivedShipmentCount: number; deliveredEquipmentCount: number; lastShipmentDate?: string | null; grossProfit: number; grossMargin?: number | null; cashNetInflow: number; warnings: FinanceConsistencyWarning[]; receivables: ReceivableSummary[]; purchases: PurchaseOrderSummary[]; payables: PayableSummary[]; receiptAllocations: ProjectReceiptAllocationSummary[]; paymentAllocations: ProjectPaymentAllocationSummary[]; shipments: ProjectShipmentSummary[] }
export interface CompanyFinanceSummary { asOfDate: string; receivableAmount: number; receivableOutstanding: number; receivableOverdue: number; cashReceivedThisMonth: number; cashReceivedYearToDate: number; receivedAllocatedThisMonth: number; receivedAllocatedYearToDate: number; purchaseThisMonth: number; purchaseYearToDate: number; payableOutstanding: number; payableOverdue: number; cashPaidThisMonth: number; cashPaidYearToDate: number; paidAllocatedThisMonth: number; paidAllocatedYearToDate: number; activeProjectContractAmount: number; estimatedGrossProfit: number; estimatedGrossMargin?: number | null; shipmentThisMonth: number; cashNetFlowThisMonth: number; warnings: FinanceConsistencyWarning[] }
export interface FinanceAgingBucket { bucket: 'NotDue' | '1-30' | '31-60' | '61-90' | '90+'; amount: number; itemCount: number }
export interface FinanceAgingOverview { asOfDate: string; totalOutstanding: number; buckets: FinanceAgingBucket[] }
export type FinanceProjectRankingMetric = 'contractAmount' | 'grossProfit' | 'grossMargin' | 'outstandingAmount' | 'overdueAmount'
export interface FinanceCashFlowPoint { month: string; receivedAmount: number; paidAmount: number; netAmount: number }
export interface FinanceRiskAlert { code: string; title: string; itemCount: number; amount: number; severity: 'Danger' | 'Warning'; targetPath: string }
export interface FinanceOverdueReceivableRow { receivableId: number; receivableCode: string; customerId: number; customerName: string; projectId: number; projectCode: string; projectName: string; dueDate: string; overdueDays: number; remainingAmount: number }
export interface FinanceOverduePayableRow { payableId: number; payableCode: string; supplierId: number; supplierName: string; projectId: number; projectCode: string; projectName: string; dueDate: string; overdueDays: number; remainingAmount: number }
export interface FinanceProjectRankingRow { projectId: number; projectCode: string; projectName: string; customerId: number; customerName: string; projectStatus: 'Planning' | 'Active' | 'OnHold' | 'Completed'; contractAmount: number; purchaseAmount: number; grossProfit: number; grossMargin?: number | null; receivableOutstandingAmount: number; receivableOverdueAmount: number }
export interface FinanceCustomerReceivableRankingRow { customerId: number; customerCode: string; customerName: string; contractAmount: number; receivableAmount: number; outstandingAmount: number; overdueAmount: number; cashReceivedAmount: number; unallocatedReceiptAmount: number }
export interface FinanceSupplierPayableRankingRow { supplierId: number; supplierCode: string; supplierName: string; purchaseAmount: number; payableAmount: number; outstandingAmount: number; overdueAmount: number; cashPaidAmount: number; allocatedPaidAmount: number; unallocatedPaymentAmount: number }
export interface FinanceDashboardSnapshot { asOfDate: string; generatedAtUtc: string; summary: CompanyFinanceSummary; receivableAging: FinanceAgingOverview; payableAging: FinanceAgingOverview; cashFlowTrend: FinanceCashFlowPoint[]; risks: FinanceRiskAlert[]; overdueReceivables: FinanceOverdueReceivableRow[]; overduePayables: FinanceOverduePayableRow[]; projectRanking: FinanceProjectRankingRow[]; projectRankingMetric: FinanceProjectRankingMetric; customerReceivableRanking: FinanceCustomerReceivableRankingRow[]; supplierPayableRanking: FinanceSupplierPayableRankingRow[] }
export interface ReceivablePlanItemInput { receivableType: ReceivableType; title: string; amount: number; dueDate: string; remark?: string }
