using FlowHearth.Application.Common;

namespace FlowHearth.Application.Finance;

public interface IReceivableRepository
{
    Task<PagedResult<ReceivableSummary>> ListReceivablesAsync(
        ReceivableListCriteria criteria,
        CancellationToken cancellationToken);
    Task<ReceivableDetails?> GetReceivableAsync(
        ulong receivableId,
        DateOnly businessDate,
        CancellationToken cancellationToken);
    Task<ReceivableDetails> CreateReceivableAsync(
        ReceivableWriteData data,
        CancellationToken cancellationToken);
    Task<ReceivableDetails?> UpdateReceivableAsync(
        ulong receivableId,
        ReceivableWriteData data,
        CancellationToken cancellationToken);
    Task<ReceivableDetails?> SetReceivableArchivedAsync(
        ulong receivableId,
        SetFinanceArchiveData data,
        DateOnly businessDate,
        CancellationToken cancellationToken);

    Task<PagedResult<ReceiptSummary>> ListReceiptsAsync(
        int page,
        int pageSize,
        string? search,
        FinanceArchiveMode archiveMode,
        ulong? customerId,
        DateOnly? dateFrom,
        DateOnly? dateTo,
        bool? hasUnallocated,
        string sortBy,
        bool sortDescending,
        CancellationToken cancellationToken);
    Task<ReceiptDetails?> GetReceiptAsync(
        ulong receiptId,
        CancellationToken cancellationToken);
    Task<ReceiptDetails> CreateReceiptAsync(
        ReceiptWriteData data,
        CancellationToken cancellationToken);
    Task<ReceiptDetails?> UpdateReceiptAsync(
        ulong receiptId,
        ReceiptWriteData data,
        CancellationToken cancellationToken);
    Task<ReceiptDetails?> SetReceiptArchivedAsync(
        ulong receiptId,
        SetFinanceArchiveData data,
        CancellationToken cancellationToken);
    Task<ReceiptDetails?> AllocateReceiptAsync(
        ulong receiptId,
        ReceiptAllocationWriteData data,
        CancellationToken cancellationToken);
    Task<ReceiptDetails?> CancelReceiptAllocationAsync(
        ulong receiptId,
        ulong allocationId,
        ulong version,
        ulong actorUserId,
        DateTime nowUtc,
        CancellationToken cancellationToken);
}

public interface IReceivableService
{
    Task<PagedResult<ReceivableSummary>> ListReceivablesAsync(
        int page,
        int pageSize,
        string? search,
        string? archive,
        ulong? customerId,
        ulong? projectId,
        string? status,
        string? receivableType,
        DateOnly? dueFrom,
        DateOnly? dueTo,
        bool? overdueOnly,
        string? sortBy,
        bool sortDescending,
        CancellationToken cancellationToken);
    Task<ReceivableDetails> GetReceivableAsync(
        ulong receivableId,
        CancellationToken cancellationToken);
    Task<ReceivableDetails> CreateReceivableAsync(
        CreateReceivableCommand command,
        ulong actorUserId,
        CancellationToken cancellationToken);
    Task<ReceivableDetails> UpdateReceivableAsync(
        ulong receivableId,
        UpdateReceivableCommand command,
        ulong actorUserId,
        CancellationToken cancellationToken);
    Task<ReceivableDetails> SetReceivableArchivedAsync(
        ulong receivableId,
        bool archived,
        FinanceVersionCommand command,
        ulong actorUserId,
        CancellationToken cancellationToken);

    Task<PagedResult<ReceiptSummary>> ListReceiptsAsync(
        int page,
        int pageSize,
        string? search,
        string? archive,
        ulong? customerId,
        DateOnly? dateFrom,
        DateOnly? dateTo,
        bool? hasUnallocated,
        string? sortBy,
        bool sortDescending,
        CancellationToken cancellationToken);
    Task<ReceiptDetails> GetReceiptAsync(
        ulong receiptId,
        CancellationToken cancellationToken);
    Task<ReceiptDetails> CreateReceiptAsync(
        CreateReceiptCommand command,
        ulong actorUserId,
        CancellationToken cancellationToken);
    Task<ReceiptDetails> UpdateReceiptAsync(
        ulong receiptId,
        UpdateReceiptCommand command,
        ulong actorUserId,
        CancellationToken cancellationToken);
    Task<ReceiptDetails> SetReceiptArchivedAsync(
        ulong receiptId,
        bool archived,
        FinanceVersionCommand command,
        ulong actorUserId,
        CancellationToken cancellationToken);
    Task<ReceiptDetails> AllocateReceiptAsync(
        ulong receiptId,
        AllocateReceiptCommand command,
        ulong actorUserId,
        CancellationToken cancellationToken);
    Task<ReceiptDetails> CancelReceiptAllocationAsync(
        ulong receiptId,
        ulong allocationId,
        CancelAllocationCommand command,
        ulong actorUserId,
        CancellationToken cancellationToken);
}
