@FlowHearth_Api_HostAddress = http://localhost:5100

GET {{FlowHearth_Api_HostAddress}}/health/live
Accept: application/json

###

GET {{FlowHearth_Api_HostAddress}}/health/ready
Accept: application/json
